
##### 20250721
cd /quobyte/bcmeyersgrp/jwahsieh/Triticum_turgidum_Kronos_liftover/blast/test
##### Step 1. precursor miRNA blastn Short

Rscript premiRNA_BLAST_pipeline.R \
  Ttu_Svevov1_premiRNA_SB_to_Kronos \
  /quobyte/bcmeyersgrp/jwahsieh/genome/Triticum_turgidum_Kronos/final/Ttu_Kronos_genome_db \
  /quobyte/bcmeyersgrp/jwahsieh/genome/Triticum_turgidum_Kronos/final/Ttu_Kronos_genome_clean.fa \
  /quobyte/bcmeyersgrp/jwahsieh/Triticum_turgidum_Kronos_liftover/Ttu_Svevov1_premiRNA_SB.fa \
  /quobyte/bcmeyersgrp/jwahsieh/Triticum_turgidum_Kronos_liftover/Ttu_Svevov1_premiRNA_SB_strand.bed \
  /quobyte/bcmeyersgrp/jwahsieh/genome/Triticum_turgidum/final/Ttu_Svevov1_genome_clean.fa.fai \
  Svevo \
  Kronos \
  /quobyte/bcmeyersgrp/jwahsieh/Triticum_turgidum_Kronos_liftover/blast/test

##### Step 2. miRNA blastn Short


Rscript miRNA_short_BLAST_pipeline.R /quobyte/bcmeyersgrp/jwahsieh/Triticum_turgidum_Kronos_liftover/blast/test/Supplementary_DataSet_S1.xlsx \
  T.turgidum \
  Ttu_Svevov1_miRNA_SB_to_Kronos \
  /quobyte/bcmeyersgrp/jwahsieh/genome/Triticum_turgidum_Kronos/final/Ttu_Kronos_genome_db \
  /quobyte/bcmeyersgrp/jwahsieh/genome/Triticum_turgidum_Kronos/final/Ttu_Kronos_genome_clean.fa \
  /quobyte/bcmeyersgrp/jwahsieh/Triticum_turgidum_Kronos_liftover/blast/test/Ttu_Svevov1_premiRNA_SB_to_Kronos_blast.bed

# Ttu_Svevov1_premiRNA_SB_to_Kronos.bed is generated by Step1



##### Step 3. Run ShortStack for targeted loci
cd /quobyte/bcmeyersgrp/jwahsieh/Triticum_turgidum_Kronos_liftover/blast/

nohup ShortStack --dicermin 20 --dicermax 24 --mmap u --mincov 1.0 --pad 75 --threads 20 --dn_mirna \
	--known_miRNAs /quobyte/bcmeyersgrp/jwahsieh/processed_results/202507_Tmonocuccum/miRBasePlantMirnas.fa \
	--outdir 20250717_Shorstack404_locifile \
	--locifile Ttu_Svevov1_premiRNA_SB_to_Kronos_blast.bed \
	--readfile *.fq \
	--genomefile /quobyte/bcmeyersgrp/jwahsieh/genome/Triticum_turgidum_Kronos/final/Ttu_Kronos_genome_clean.fa &


bash ShortStackResults_bed_fasta.sh \
  /quobyte/bcmeyersgrp/jwahsieh/Triticum_turgidum_Kronos_liftover/blast/20250717_Shorstack404_locifile/Results.gff3 \
  /quobyte/bcmeyersgrp/jwahsieh/genome/Triticum_turgidum_Kronos/final/Ttu_Kronos_genome_clean.fa \
  /quobyte/bcmeyersgrp/jwahsieh/Triticum_turgidum_Kronos_liftover/blast/20250717_Shorstack404_locifile/Results



##### Step 4. Generate Summary table and GFF table
cd /quobyte/bcmeyersgrp/jwahsieh/Triticum_turgidum_Kronos_liftover/blast/test

Rscript Summary_RPM_miRNA.R \
  /quobyte/bcmeyersgrp/jwahsieh/Triticum_turgidum_Kronos_liftover/blast/20250717_Shorstack404_locifile/Results.gff3 \
  /quobyte/bcmeyersgrp/jwahsieh/Triticum_turgidum_Kronos_liftover/blast/Ttu_Svevov1_miRNA_Kronos_merged.txt \
  /quobyte/bcmeyersgrp/jwahsieh/Triticum_turgidum_Kronos_liftover/blast/20250717_Shorstack404_locifile/miRNA_kronos.gff3 \
  /quobyte/bcmeyersgrp/jwahsieh/Triticum_turgidum_Kronos_liftover/blast/20250717_Shorstack404_locifile/Results.fa \
  /quobyte/bcmeyersgrp/jwahsieh/Triticum_turgidum_Kronos_liftover/blast/20250717_Shorstack404_locifile/mir.fasta \
  /quobyte/bcmeyersgrp/jwahsieh/Triticum_turgidum_Kronos_liftover/blast/20250717_Shorstack404_locifile/Counts.txt \
  /quobyte/bcmeyersgrp/jwahsieh/Ttu_Kronos_miRNA/libs/fasta_output/miRScore_output/Final/Remap_genome/allcount_names.txt \
  /quobyte/bcmeyersgrp/jwahsieh/Ttu_Kronos_miRNA/libs/fasta_output/Name.csv


